{% set name = "boltons" %}
{% set version = "19.1.0" %}
{% set hash_type = "sha256" %}
{% set hash = "ae59ff28466caacaa0b55a536d41c37c11192475804bdbfeb076172e80a5c1b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mahmoud/{{ name }}/archive/{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - boltons
    - tests
    - pytest.ini
  requires:
    - pytest
  commands:
    - 'py.test --doctest-modules boltons tests'

about:
  home: https://github.com/mahmoud/boltons
  license: BSD 3-Clause
  summary: >
    boltons should be builtins. Boltons is a set of over 160 BSD-licensed,
    pure-Python utilities in the same spirit as--and yet conspicuously
    missing from--the standard library.
