{% set name = "boltons" %}
{% set version = "21.0.0" %}
{% set sha256 = "9f29e135661071968b9cea1783dd5bd2403b2a141ccd5f5637692fc544bcc4db" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mahmoud/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - boltons
    - tests
    - pytest.ini
  requires:
    - pytest
  commands:
    - py.test --doctest-modules boltons tests

about:
  home: https://github.com/mahmoud/boltons
  license: BSD-3-Clause
  license_file: LICENSE
  summary: >
    boltons should be builtins. Boltons is a set of over 160 BSD-licensed, pure-Python utilities in the same spirit as--and yet conspicuously missing from--the standard library.
